---
title: "READ ME - Project Set Up"
format: 
  html:
    embed-resources: false
editor: visual
cache: false
echo: false
include: false
---

The collaboration project contains all R files, documents, analysis and calculations undertaken throughout the project.

The files have the following structure:

### Initial Data From Collaborator

This file contains the excel spreadsheet provided to us by Karl.

### Cleaned Data

The data provided to us was in multiple tabs so it was combined into long data list ready to be inputted into R.

### R

The R File contains the files used to undertaken the projects given to us by Karl. There are:

-   Gene Expression - Karl 1 Analysis.Rmd

-   Karl Task 2. Rmd

-   Karl Task 3.Rmd

-   Karl Task 4 Attempt 2.Rmd

-   IMRaD Report 2.Rmd

The processes undertaken to produce each one of these files can be found in the README - what I did.qmd

### Created Files

This file contains all the outputted files required for submission. The files were:

-   Karl Plot.tiff (From Task 2)

-   IMRaD Report Final.pdf (From Task 4)

-   Presentation Gene Expression Data.pptx (From Task 1)

    -   Gene-Expression---Karl-1-Analysis.pdf

    -   Gene-Expression---Karl-1-Analysis.docx

-   Karl Task 3.pdf (From Task 3)

### Resources

-   This folder contains any resources from the collaborator. It contains the plot we were required to recreate for task 2.

### Read Me Quarto Files

This file contains the .qmd versions of the README files. The HTML's of the README's are in the main file.
